### ISSUE TITLE
I am not sure if it is happing to everyone or just me

### ISSUE THREAD

**Issue by anup2050** [shadowmoose/RedditDownloader#144]
### Describe the bug
any mp4 media downloaded by rdm is currept in middle

### Environment Info
windows 10
RDM LATEST VERSION

### Additional context
I checked with a lot to subreddits but it happens with every single one of them
![vlcsnap-00001](https://user-images.githubusercontent.com/66366537/83885583-2bb3e700-a764-11ea-9739-0fb19e77bac2.png)

**Comment by shadowmoose** [comment]
Hey, depending on the site this will most likely be handled by the youtube-dl project. 

If they corrupted videos are from the same site, my guess is that their handler for that website is broken. If the videos are corrupted from multiple different sites, it may be an issue with your system's ffmpeg library - or something else. Either way, since RMD doesn't handle and video encoding, this unfortunately looks like it extends beyond anything RMD can solve for you.
