### ISSUE TITLE
Clarification and little problem

### ISSUE THREAD

**Issue by vincenzogianfelice** [shadowmoose/RedditDownloader#196]
Hi. I have recently been trying this tool and I noticed that when the download starts it is not possible to stop it. Here, I was wondering if it was possible to add a "stop button" and maybe another button to resume the download.
Also, there is one other thing I wanted to ask you... _**I state that reddit do not know him very well ... in fact in the "Sources" section I am lost.**_
So I wanted to ask you two things:

- If I wanted to download EVERYTHING from a SINGLE PROFILE, which source should I enter? (thank you)

- I noticed that when it finishes downloading and reports the number of downloaded files, it doesn't actually coincide when I go to check the files. The downloaded files are always more "few" than those reported by the tool. This is normal? (I also disabled the deduplication option)

Thanks and sorry for my English

**Comment by shadowmoose** [comment]
Hello, thanks for the questions.

To answer your first question, it is not currently possible to stop RMD without terminating the program. This is fixed in the new rewrite, but will not be available for a while. The rewrite will also allow users to terminate individual downloads.

As for downloading a profile's data, you should use the Source named ["A User's Submission and/or Comment History"](https://shadowmoose.github.io/RedditDownloader/Getting_Started/Sources/#users-submission-comment-history) source. This will download all media they have posted in submissions or comments.

The download counter may be slightly off in this version of RMD, depending on a number of things that can happen while downloading files. RMD always ignores duplicate URLs, so it is possible that could throw off the count as well. Typically, RMD is more accurate at counting the number of posts it has scanned, rather than the total number of actual files downloaded. This is also something that will change in the RMD rewrite.

Thanks again, and let me know if you have any more questions.

**Comment by vincenzogianfelice** [comment]
> As for downloading a profile's data, you should use the Source named "A User's Submission and/or Comment History" source. This will download all media they have posted in submissions or comments.

Thanks,.. i'll try and let you know in case of problems

Another thing I wanted to ask you is if it is possible to add the possibility of being able to download two or more sources at the same time.

Thanks.

**Comment by shadowmoose** [comment]
Currently it is not possible to scan more than one at a time, but they will all scan sequentially and download concurrently. This will be changed in the rewrite.

**Comment by vincenzogianfelice** [comment]
I imagined .... but I wanted to tell you in order to evaluate the implementation.

However, I have tried many sources but they all report a different number of files (found). What you said earlier reported only 100 files, while the "Pushfit" source reports much more. Here, I wonder how it is possible, given that it should download all the data, regardless, of that specific user?

**Comment by shadowmoose** [comment]
PushShift can find deleted posts, and also does not have the ~1000 post scan limit that Reddit's API has. It is probably simply finding more posts to download.
