### ISSUE TITLE
Do you accept contributions?

### ISSUE THREAD

**Issue by arkadyt** [shadowmoose/RedditDownloader#40]
I was thinking about helping you out with the front-end.

What do you say?

**Comment by shadowmoose** [comment]
Certainly, feel free to offer any changes you'd like to make!

**Comment by arkadyt** [comment]
@shadowmoose, are you strongly determined on using eel?
If you were to switch to a more modern setup (like the one using Flask), it'd be possible to painlessly introduce many awesome js modules, which would drastically speed up the development process.
This would also make the contributing a lot more accessible for all the other devs in the future.

**Comment by shadowmoose** [comment]
I'm not determined to keep using Eel, it was just more convenient at the time. I initially planned to support two-way communication, but quickly realized that wouldn't be required. 

That said, almost all of the required functionality is already implemented (and working well) through Eel, so I probably won't personally rewrite it unless somebody provides a compelling reason. I'd like to avoid delaying the 3.0 UI rollout too much, because it's currently sitting in a (mostly) completed state.

Are there any modules you specifically have in mind? I'm certainly open to making the change if there is something to gain from doing so.

**Comment by arkadyt** [comment]
Yup. A quick glance over App.js render():
```
let pages = this.pages.map((p) => {
    let idx = this.pages.indexOf(p);
    if (this.state.downloading && this.pages[idx][2] === false) {
        return <li className={'inactive disabled'} key={idx}><a>{p[1]}</a></li>
    } else {
        return <li className={this.state.page === idx ? 'active' : 'inactive'} key={idx}>
            <a onClick={this._openPage.bind(this, idx)}>{p[1]}</a>
        </li>
    }
});
let eles = this.pages.map((p) => {
    let idx = this.pages.indexOf(p);
    return <div key={idx} className={this.state.page === idx ? 'active_page_container' : 'hidden'} >{p[0]}</div>
});
``` 
You could have easily avoided writing almost all of that by using [react-router](https://reacttraining.com/react-router/core/guides/philosophy). Like so:

_App.js, page switching:_
```
<Route path='/home' component={ Home } />
```
_NavBar.js (suppose you have it separately), automatic active link css management:_
```
<NavLink to='/home' onClick={ this._openPage.bind(this, idx) } />
```
To grey out the NavLink while downloading you can add the activeClassName prop:
`activeClassName={ !this.state.downloading? 'class' : null }`

Needless to say, page switching is instant as well.

There is plenty of other things that npm ecosystem offers, and that may save you a lot of time in the long run. Though I totally understand your decision, eel does its job and has already saved you time.

**P.S.** map method exposes index as a second argument:
```
arr.map((item, index) => { ... });
```

**Comment by shadowmoose** [comment]
Interesting. I was unaware such a library existed. For the most part I prefer to roll my own solution if the problem is simple enough. Wherever possible, I'd like to avoid making the project too reliant on external dependencies. I'm not looking to reinvent the wheel though, so if things can be cleaned up or optimized with external libs, I'm happy to give them a chance.

Is there a format you think would work better for passing data from Python->JS? Using Websockets does provide the advantage of rapid detection of UI disconnects, which allows RMD to (optionally) terminate itself when the UI is closed. Perhaps simple ajax requests would be more reasonable, though I'm not sure there's much benefit to switching. I'm open to suggestions.

Also, you're right about the map index. That's totally a silly oversight on my part. Good catch.

**Comment by arkadyt** [comment]
Great point! But react-router and few others are de facto the pillars of every modern react app these days and are very safe to depend on.

As for passing data from the backend, you're right, WebSockets would do the job nicely. I'd even say gracefully!

I can set everything up myself, really I just need to know that you're willing to accept the PR.

**Comment by shadowmoose** [comment]
Yep, I'll accept anything that follows the contribution guidelines.
