### ISSUE TITLE
Adding a option to remove saved items after they have been downloaded

### ISSUE THREAD

**Issue by dangledoodles** [shadowmoose/RedditDownloader#72]
### Is your feature request related to a problem? Please describe.
Because reddit only lets us download the first 1000 i have to go through all my posts and remove them for it to download the next 1000

### Describe the solution you'd like:
When setting up the program to download from your profile it could have a option to enable auto deleting of saved items once they have been downloaded

**Comment by shadowmoose** [comment]
It's a decent suggestion, but unfortunately it appears that Reddit actually trims your list randomly, after 1000 entries.
https://www.reddit.com/r/bugs/comments/7v857g/im_trying_to_bypass_the_1000_upvoted_posts_limit/

For that reason, and also because I'd rather not have to authorize RMD to perform any destructive actions, this feature won't be something I can add.
