### ISSUE TITLE
Suggestions for sorting downloads

### ISSUE THREAD

**Issue by evilmanimani** [shadowmoose/RedditDownloader#88]
Hey there, I don't see any options similar to this, so apologies if I missed it, however I'd like some sort of option to sort download files which retains the order in which they were saved, either by date saved (if that's something reddit exposes) at the start of the filename ( DD-MM-YYYY format) or just modifying the system modified date/created date to match that as well. If that's not possible, perhaps some sort of numeric ID, separate from the post ID that can be added to the start of the filename, that when sorted by will put the files in saved order.

As an aside, when trying to add [id] to the file name pattern, it just adds the text 'id', am I missing something in the formatting? Cheers.

**Comment by shadowmoose** [comment]
Hey, thanks for the suggestion.

I like the idea - that information would be useful to have - but I'm afraid Reddit simply doesn't expose that information through the API. Reddit keeps a rolling log of only ~1000 Posts from any source, and it would be difficult to synchronize against this list in follow-up runs. Additionally, given RMD's multi-threaded and multi-source nature, it is difficult to reliably determine the exact order that incoming posts were received. 

If you want to be specific about ordering, the best RMD can offer is the ```created_utc``` tag, which will be an integer value. I'll likely look at adding some pre-formatted datetime options as well, because I like that idea.

As for your last ```[id]``` issue, that's my fault. I (incorrectly) documented that tag as "id", when it really should be ```[reddit_id]``` instead. I've corrected the documentation for that problem.

**Comment by evilmanimani** [comment]
created_utc was exactly what I was looking for, thanks! Appears to be in order for the most part, now is that tag referring to the UTC time that the post was saved, or the time it was originally made? Either way, it's definitely better than what I had before.

It'd be nice to be able to define sorting further, i.e. different folders based on multiple filetypes, etc. I can do that currently with a batch file, and it looks like the program won't attempt to re-download anything if I leave the manifest file in place, so that works for the time being.

**Comment by shadowmoose** [comment]
Correct, the `created_utc` time is the creation time of the Submission/Comment. Reddit does not expose other Liked/Saved times, unfortunately. As a side note, the latest master tree has extra date and time flags implemented & documented, in case that's of additional use to you.

As for filetype sorting, that will probably have to be handled externally. Due to supporting a number of different download methods, RMD has no knowledge of the filetype before a Post is downloaded, and would likely require some extensive rewriting to do so.

To avoid collisions common in Reddit titles, RMD pre-selects all file names and folder structures before handing each Post off to a downloader thread. It's certainly possible to work around this, but the solution will either make things more complicated for the average user to configure, or will be too use-case-specific.

This is probably something I can circle back to eventually - as the next major feature I'd like to look at is post-processing options - but since it's a relatively fringe use case easily handled via an external script, I won't be looking to specifically support this in the immediate future.

In the meanwhile, as you've noticed, RMD will respect the manifest and ignore missing file paths. Sorry I can't help you more with this request right now, but I'm trying to make sure my time - for now - is spent on (finally) getting another actual release out.

**Comment by evilmanimani** [comment]
No problem at all, I've got a pretty good setup now, running smoothly. Scheduled task to run RMD via batch file which also on completion moves them with robocopy to different folders with some filetype filters, then I've got Syncthing setup to send them back to my phone. Pretty roundabout way of doing it, but it keeps a backed up copy on my PC while keeping a local copy on my phone that is miles better to browse through using a viewer of choice, compared to any of the available Reddit apps.

Thanks for the very detailed replies!
