### ISSUE TITLE
Optional seperate download folder for given source

### ISSUE THREAD

**Issue by Saortica** [shadowmoose/RedditDownloader#98]
### Is your feature request related to a problem? Please describe.

When using a source that includes a search/filter most of the reason is that I want these separate from other posts or downloads brought down. EG, waterfall pics drawn from the history of the subreddit, separate from the main downloads in the main subreddit folder (which may include all sorts of things and just from the last week or month, etc). It feels like a bit of an unnecessary burden to go and filemanage your way around this, eg, move all previous files out first, or search and move the relevant downloads with a filemanager, etc. I guess to me it seems intuitive to have a discrete search save in a discrete place instead! 

### Describe the solution you'd like:
A good way to meet this could be to be able to define directory per source (in the fields as you set up a source). I think it could be just a subfolder of the main subreddit folder. This could be optionally left blank if you're not fussed.

**Comment by Saortica** [comment]
I've found something that helps with the issue of locating separate source downloads in the meantime - name your sources usefully and use the tag source_alias at the beginning of the filename. That way they are much more easily grouped together when looking in the subreddit folder.

**Comment by shadowmoose** [comment]
Hey, sorry about the delay. 

Yes, using the source_alias tag is the intended solution to this use case. It is unlikely that I will include additional per-source path config, as that would require significant changes to the structure of RMD, as well as further complicating the setup for casual users. Since the tag can be embedded anywhere in the output path, it should suffice for most requirements.

Hopefully that solves your problem. If not, please feel free to let me know what you'd be looking for, more specifically, and I can look at add it to the backlog.

**Comment by Saortica** [comment]
The source_alias tag feature has been working fine for my needs, thanks.
